---
name: Reusable .NET Build & Verify Tests Pass - PowerShell Cmdlet Module

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      dotnet-versions:
        description: "SDK versions to install"
        required: false
        type: string
        default: 10.x
      configuration:
        description: "Build configuration"
        required: false
        type: string
        default: Release
      version:
        description: "Package version"
        required: true
        type: string
      source-directory:
        description: "Relative directory where source code is located"
        required: false
        type: string
        default: .
      artifact-name:
        description: "Name of the artifact to upload"
        required: false
        type: string
        default: Packages
      main-library-subdir:
        description: "Directory of the main library project"
        required: false
        type: string
        default: .
jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    name: Build and verify tests pass
    defaults:
      run:
        working-directory: ${{ inputs.source-directory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ inputs.dotnet-versions }}
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Restore dependencies
        shell: pwsh
        run: |
          dotnet restore

      - name: Build solution
        shell: pwsh
        run: |
          dotnet build --configuration ${{ inputs.configuration }} --no-restore

      - name: Run Xunit tests
        id: run-tests
        run: >
          dotnet test --configuration ${{ inputs.configuration }}
          --filter "Category!=Integration"
          --no-build --logger trx

      - name: Upload Xunit test results
        if: >
          ${{ steps.run-tests.outcome != 'skipped' &&
            steps.run-tests.outcome != 'cancelled' }}
        uses: actions/upload-artifact@v6
        with:
          name: test-results
          path: "**/*.trx"

      - name: Run Pester Tests
        id: run-pester-tests
        shell: pwsh
        run: |
          cd ./Tests/Pester;
          Import-Module Pester;
          $config = New-PesterConfiguration;
          $config.Run.Path = './Add-DotnetClassLibProject.Tests.ps1';
          $config.TestResult.OutputPath = 'pester-results.xml';
          $config.TestResult.OutputFormat = 'NUnitXML';
          $config.TestResult.Enabled = $true;
          Invoke-Pester -Configuration $config;

      - name: Upload Pester test results
        if: >
          ${{ steps.run-pester-tests.outcome != 'skipped' &&
            steps.run-pester-tests.outcome != 'cancelled' }}
        uses: actions/upload-artifact@v6
        with:
          name: pester-test-results
          path: "**/pester-results.xml"

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ inputs.artifact-name }}
          path: "${{ inputs.source-directory }}/${{ inputs.main-library-subdir }}/bin"
          if-no-files-found: error
